name: gotrue
description: A dart client library for the GoTrue API.
version: 0.2.0
homepage: "https://supabase.io"
repository: "https://github.com/supabase/gotrue-dart"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.0
  jwt_decode: ^0.3.1
  universal_io: ^2.0.4

dev_dependencies:
  dotenv: ^3.0.0
  lints: ^1.0.1
  test: ^1.16.4

false_secrets:
  - /infra/docker-compose.yml
