name: gotrue
description: A dart client library for the GoTrue API.
version: 0.0.1-dev.9
homepage: "https://supabase.io"
repository: "https://github.com/supabase/gotrue-dart"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.0
  sembast: ^3.0.1

dev_dependencies:
  lint: ^1.5.1
  test: ^1.16.4
